# APIs Lab

In this lab, you will work with different APIs to build datasets and perform basic analysis.

The goal is to practice how to:

- Make API requests  
- Explore JSON responses  
- Extract relevant information  
- Transform data into pandas DataFrames  
- Generate simple insights  

You will work like a data analyst using APIs data.

# Challenge 1: Pokémon Dataset & Analysis

## Goal

Build and analyze a Pokémon dataset using the API.

## Example (single request)

Below you can see how to get data for ONE Pokémon:

In [1]:
import requests

url = "https://pokeapi.co/api/v2/pokemon/1"

response = requests.get(url)
data = response.json()

data

{'id': 1,
 'name': 'bulbasaur',
 'base_experience': 64,
 'height': 7,
 'is_default': True,
 'order': 1,
 'weight': 69,
 'abilities': [{'is_hidden': False,
   'slot': 1,
   'ability': {'name': 'overgrow',
    'url': 'https://pokeapi.co/api/v2/ability/65/'}},
  {'is_hidden': True,
   'slot': 3,
   'ability': {'name': 'chlorophyll',
    'url': 'https://pokeapi.co/api/v2/ability/34/'}}],
 'past_abilities': [{'generation': {'name': 'generation-iv',
    'url': 'https://pokeapi.co/api/v2/generation/4/'},
   'abilities': [{'is_hidden': True, 'slot': 3, 'ability': None}]}],
 'forms': [{'name': 'bulbasaur',
   'url': 'https://pokeapi.co/api/v2/pokemon-form/1/'}],
 'game_indices': [{'game_index': 153,
   'version': {'name': 'red', 'url': 'https://pokeapi.co/api/v2/version/1/'}},
  {'game_index': 153,
   'version': {'name': 'blue', 'url': 'https://pokeapi.co/api/v2/version/2/'}},
  {'game_index': 153,
   'version': {'name': 'yellow',
    'url': 'https://pokeapi.co/api/v2/version/3/'}},
  {'game_index': 1,
   'version': {'name': 'gold', 'url': 'https://pokeapi.co/api/v2/version/4/'}},
  {'game_index': 1,
   'version': {'name': 'silver',
    'url': 'https://pokeapi.co/api/v2/version/5/'}},
  {'game_index': 1,
   'version': {'name': 'crystal',
    'url': 'https://pokeapi.co/api/v2/version/6/'}},
  {'game_index': 1,
   'version': {'name': 'ruby', 'url': 'https://pokeapi.co/api/v2/version/7/'}},
  {'game_index': 1,
   'version': {'name': 'sapphire',
    'url': 'https://pokeapi.co/api/v2/version/8/'}},
  {'game_index': 1,
   'version': {'name': 'emerald',
    'url': 'https://pokeapi.co/api/v2/version/9/'}},
  {'game_index': 1,
   'version': {'name': 'firered',
    'url': 'https://pokeapi.co/api/v2/version/10/'}},
  {'game_index': 1,
   'version': {'name': 'leafgreen',
    'url': 'https://pokeapi.co/api/v2/version/11/'}},
  {'game_index': 1,
   'version': {'name': 'diamond',
    'url': 'https://pokeapi.co/api/v2/version/12/'}},
  {'game_index': 1,
   'version': {'name': 'pearl',
    'url': 'https://pokeapi.co/api/v2/version/13/'}},
  {'game_index': 1,
   'version': {'name': 'platinum',
    'url': 'https://pokeapi.co/api/v2/version/14/'}},
  {'game_index': 1,
   'version': {'name': 'heartgold',
    'url': 'https://pokeapi.co/api/v2/version/15/'}},
  {'game_index': 1,
   'version': {'name': 'soulsilver',
    'url': 'https://pokeapi.co/api/v2/version/16/'}},
  {'game_index': 1,
   'version': {'name': 'black',
    'url': 'https://pokeapi.co/api/v2/version/17/'}},
  {'game_index': 1,
   'version': {'name': 'white',
    'url': 'https://pokeapi.co/api/v2/version/18/'}},
  {'game_index': 1,
   'version': {'name': 'black-2',
    'url': 'https://pokeapi.co/api/v2/version/21/'}},
  {'game_index': 1,
   'version': {'name': 'white-2',
    'url': 'https://pokeapi.co/api/v2/version/22/'}},
  {'game_index': 1,
   'version': {'name': 'x', 'url': 'https://pokeapi.co/api/v2/version/23/'}},
  {'game_index': 1,
   'version': {'name': 'y', 'url': 'https://pokeapi.co/api/v2/version/24/'}},
  {'game_index': 1,
   'version': {'name': 'omega-ruby',
    'url': 'https://pokeapi.co/api/v2/version/25/'}},
  {'game_index': 1,
   'version': {'name': 'alpha-sapphire',
    'url': 'https://pokeapi.co/api/v2/version/26/'}},
  {'game_index': 1,
   'version': {'name': 'sun', 'url': 'https://pokeapi.co/api/v2/version/27/'}},
  {'game_index': 1,
   'version': {'name': 'moon',
    'url': 'https://pokeapi.co/api/v2/version/28/'}},
  {'game_index': 1,
   'version': {'name': 'ultra-sun',
    'url': 'https://pokeapi.co/api/v2/version/29/'}},
  {'game_index': 1,
   'version': {'name': 'ultra-moon',
    'url': 'https://pokeapi.co/api/v2/version/30/'}},
  {'game_index': 1,
   'version': {'name': 'lets-go-pikachu',
    'url': 'https://pokeapi.co/api/v2/version/31/'}},
  {'game_index': 1,
   'version': {'name': 'lets-go-eevee',
    'url': 'https://pokeapi.co/api/v2/version/32/'}},
  {'game_index': 1,
   'version': {'name': 'sword',
    'url': 'https://pokeapi.co/api/v2/version/33/'}},
  {'game_index': 1,
   'version': {'name': 'shield',
    'url': 'https://pokeapi.co/api/v2/version/34/'}},
  {'game_index': 1,
   'version': {'name': 'the-isle-of-armor-sword',
    'url': 'https://pokeapi.co/api/v2/version/35/'}},
  {'game_index': 1,
   'version': {'name': 'the-crown-tundra-sword',
    'url': 'https://pokeapi.co/api/v2/version/36/'}},
  {'game_index': 1,
   'version': {'name': 'brilliant-diamond',
    'url': 'https://pokeapi.co/api/v2/version/37/'}},
  {'game_index': 1,
   'version': {'name': 'shining-pearl',
    'url': 'https://pokeapi.co/api/v2/version/38/'}},
  {'game_index': 1,
   'version': {'name': 'legends-arceus',
    'url': 'https://pokeapi.co/api/v2/version/39/'}},
  {'game_index': 1,
   'version': {'name': 'scarlet',
    'url': 'https://pokeapi.co/api/v2/version/40/'}},
  {'game_index': 1,
   'version': {'name': 'violet',
    'url': 'https://pokeapi.co/api/v2/version/41/'}},
  {'game_index': 1,
   'version': {'name': 'the-teal-mask-scarlet',
    'url': 'https://pokeapi.co/api/v2/version/42/'}},
  {'game_index': 1,
   'version': {'name': 'the-indigo-disk-scarlet',
    'url': 'https://pokeapi.co/api/v2/version/43/'}},
  {'game_index': 153,
   'version': {'name': 'red-japan',
    'url': 'https://pokeapi.co/api/v2/version/44/'}},
  {'game_index': 153,
   'version': {'name': 'green-japan',
    'url': 'https://pokeapi.co/api/v2/version/45/'}},
  {'game_index': 153,
   'version': {'name': 'blue-japan',
    'url': 'https://pokeapi.co/api/v2/version/46/'}},
  {'game_index': 1,
   'version': {'name': 'legends-za',
    'url': 'https://pokeapi.co/api/v2/version/47/'}},
  {'game_index': 1,
   'version': {'name': 'mega-dimension',
    'url': 'https://pokeapi.co/api/v2/version/48/'}}],
 'held_items': [],
 'location_area_encounters': 'https://pokeapi.co/api/v2/pokemon/1/encounters',
 'moves': [{'move': {'name': 'razor-wind',
    'url': 'https://pokeapi.co/api/v2/move/13/'},
   'version_group_details': [{'level_learned_at': 0,
     'version_group': {'name': 'gold-silver',
      'url': 'https://pokeapi.co/api/v2/version-group/3/'},
     'move_learn_method': {'name': 'egg',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/2/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'crystal',
      'url': 'https://pokeapi.co/api/v2/version-group/4/'},
     'move_learn_method': {'name': 'egg',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/2/'},
     'order': None}]},
  {'move': {'name': 'swords-dance',
    'url': 'https://pokeapi.co/api/v2/move/14/'},
   'version_group_details': [{'level_learned_at': 0,
     'version_group': {'name': 'red-blue',
      'url': 'https://pokeapi.co/api/v2/version-group/1/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'yellow',
      'url': 'https://pokeapi.co/api/v2/version-group/2/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version-group/6/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'firered-leafgreen',
      'url': 'https://pokeapi.co/api/v2/version-group/7/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'diamond-pearl',
      'url': 'https://pokeapi.co/api/v2/version-group/8/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version-group/9/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'heartgold-soulsilver',
      'url': 'https://pokeapi.co/api/v2/version-group/10/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'black-white',
      'url': 'https://pokeapi.co/api/v2/version-group/11/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'black-2-white-2',
      'url': 'https://pokeapi.co/api/v2/version-group/14/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'x-y',
      'url': 'https://pokeapi.co/api/v2/version-group/15/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'omega-ruby-alpha-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/16/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'sun-moon',
      'url': 'https://pokeapi.co/api/v2/version-group/17/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'ultra-sun-ultra-moon',
      'url': 'https://pokeapi.co/api/v2/version-group/18/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'sword-shield',
      'url': 'https://pokeapi.co/api/v2/version-group/20/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'brilliant-diamond-shining-pearl',
      'url': 'https://pokeapi.co/api/v2/version-group/23/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'scarlet-violet',
      'url': 'https://pokeapi.co/api/v2/version-group/25/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'red-green-japan',
      'url': 'https://pokeapi.co/api/v2/version-group/28/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'blue-japan',
      'url': 'https://pokeapi.co/api/v2/version-group/29/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None}]},
  {'move': {'name': 'cut', 'url': 'https://pokeapi.co/api/v2/move/15/'},
   'version_group_details': [{'level_learned_at': 0,
     'version_group': {'name': 'red-blue',
      'url': 'https://pokeapi.co/api/v2/version-group/1/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'yellow',
      'url': 'https://pokeapi.co/api/v2/version-group/2/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'gold-silver',
      'url': 'https://pokeapi.co/api/v2/version-group/3/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'crystal',
      'url': 'https://pokeapi.co/api/v2/version-group/4/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'ruby-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/5/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version-group/6/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'firered-leafgreen',
      'url': 'https://pokeapi.co/api/v2/version-group/7/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'diamond-pearl',
      'url': 'https://pokeapi.co/api/v2/version-group/8/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version-group/9/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'heartgold-soulsilver',
      'url': 'https://pokeapi.co/api/v2/version-group/10/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'black-white',
      'url': 'https://pokeapi.co/api/v2/version-group/11/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'colosseum',
      'url': 'https://pokeapi.co/api/v2/version-group/12/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'xd',
      'url': 'https://pokeapi.co/api/v2/version-group/13/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'black-2-white-2',
      'url': 'https://pokeapi.co/api/v2/version-group/14/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'x-y',
      'url': 'https://pokeapi.co/api/v2/version-group/15/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'omega-ruby-alpha-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/16/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'brilliant-diamond-shining-pearl',
      'url': 'https://pokeapi.co/api/v2/version-group/23/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'red-green-japan',
      'url': 'https://pokeapi.co/api/v2/version-group/28/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'blue-japan',
      'url': 'https://pokeapi.co/api/v2/version-group/29/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None}]},
  {'move': {'name': 'bind', 'url': 'https://pokeapi.co/api/v2/move/20/'},
   'version_group_details': [{'level_learned_at': 0,
     'version_group': {'name': 'black-2-white-2',
      'url': 'https://pokeapi.co/api/v2/version-group/14/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'omega-ruby-alpha-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/16/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'ultra-sun-ultra-moon',
      'url': 'https://pokeapi.co/api/v2/version-group/18/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None}]},
  {'move': {'name': 'vine-whip', 'url': 'https://pokeapi.co/api/v2/move/22/'},
   'version_group_details': [{'level_learned_at': 13,
     'version_group': {'name': 'red-blue',
      'url': 'https://pokeapi.co/api/v2/version-group/1/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 13,
     'version_group': {'name': 'yellow',
      'url': 'https://pokeapi.co/api/v2/version-group/2/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 10,
     'version_group': {'name': 'gold-silver',
      'url': 'https://pokeapi.co/api/v2/version-group/3/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 10,
     'version_group': {'name': 'crystal',
      'url': 'https://pokeapi.co/api/v2/version-group/4/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 10,
     'version_group': {'name': 'ruby-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/5/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 10,
     'version_group': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version-group/6/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 10,
     'version_group': {'name': 'firered-leafgreen',
      'url': 'https://pokeapi.co/api/v2/version-group/7/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 9,
     'version_group': {'name': 'diamond-pearl',
      'url': 'https://pokeapi.co/api/v2/version-group/8/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 9,
     'version_group': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version-group/9/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},

## Tasks

1. Using the example above, get data for Pokémon IDs from 1 to 151

2. Extract:
   - name
   - height
   - weight
   - base_experience
   - first type

3. Create a DataFrame

4. Add a new column:
   - weight_kg (divide weight by 10)

5. Answer:
   - Which Pokémon is the heaviest?
   - What is the average weight?
   - How many Pokémon are there per type?

6. Answer:
   - Which type has the highest average weight?

In [2]:
"Using the example above, get data for Pokémon IDs from 1 to 151"
import pandas as pd
import time
from IPython.display import JSON
url = "https://pokeapi.co/api/v2/pokemon"

response = requests.get("https://pokeapi.co/api/v2/pokemon?limit=151&offset=0", timeout=10)
data = response.json()
display(data)

{'count': 1351,
 'next': 'https://pokeapi.co/api/v2/pokemon?offset=151&limit=151',
 'previous': None,
 'results': [{'name': 'bulbasaur',
   'url': 'https://pokeapi.co/api/v2/pokemon/1/'},
  {'name': 'ivysaur', 'url': 'https://pokeapi.co/api/v2/pokemon/2/'},
  {'name': 'venusaur', 'url': 'https://pokeapi.co/api/v2/pokemon/3/'},
  {'name': 'charmander', 'url': 'https://pokeapi.co/api/v2/pokemon/4/'},
  {'name': 'charmeleon', 'url': 'https://pokeapi.co/api/v2/pokemon/5/'},
  {'name': 'charizard', 'url': 'https://pokeapi.co/api/v2/pokemon/6/'},
  {'name': 'squirtle', 'url': 'https://pokeapi.co/api/v2/pokemon/7/'},
  {'name': 'wartortle', 'url': 'https://pokeapi.co/api/v2/pokemon/8/'},
  {'name': 'blastoise', 'url': 'https://pokeapi.co/api/v2/pokemon/9/'},
  {'name': 'caterpie', 'url': 'https://pokeapi.co/api/v2/pokemon/10/'},
  {'name': 'metapod', 'url': 'https://pokeapi.co/api/v2/pokemon/11/'},
  {'name': 'butterfree', 'url': 'https://pokeapi.co/api/v2/pokemon/12/'},
  {'name': 'weedle', 'url': 'https://pokeapi.co/api/v2/pokemon/13/'},
  {'name': 'kakuna', 'url': 'https://pokeapi.co/api/v2/pokemon/14/'},
  {'name': 'beedrill', 'url': 'https://pokeapi.co/api/v2/pokemon/15/'},
  {'name': 'pidgey', 'url': 'https://pokeapi.co/api/v2/pokemon/16/'},
  {'name': 'pidgeotto', 'url': 'https://pokeapi.co/api/v2/pokemon/17/'},
  {'name': 'pidgeot', 'url': 'https://pokeapi.co/api/v2/pokemon/18/'},
  {'name': 'rattata', 'url': 'https://pokeapi.co/api/v2/pokemon/19/'},
  {'name': 'raticate', 'url': 'https://pokeapi.co/api/v2/pokemon/20/'},
  {'name': 'spearow', 'url': 'https://pokeapi.co/api/v2/pokemon/21/'},
  {'name': 'fearow', 'url': 'https://pokeapi.co/api/v2/pokemon/22/'},
  {'name': 'ekans', 'url': 'https://pokeapi.co/api/v2/pokemon/23/'},
  {'name': 'arbok', 'url': 'https://pokeapi.co/api/v2/pokemon/24/'},
  {'name': 'pikachu', 'url': 'https://pokeapi.co/api/v2/pokemon/25/'},
  {'name': 'raichu', 'url': 'https://pokeapi.co/api/v2/pokemon/26/'},
  {'name': 'sandshrew', 'url': 'https://pokeapi.co/api/v2/pokemon/27/'},
  {'name': 'sandslash', 'url': 'https://pokeapi.co/api/v2/pokemon/28/'},
  {'name': 'nidoran-f', 'url': 'https://pokeapi.co/api/v2/pokemon/29/'},
  {'name': 'nidorina', 'url': 'https://pokeapi.co/api/v2/pokemon/30/'},
  {'name': 'nidoqueen', 'url': 'https://pokeapi.co/api/v2/pokemon/31/'},
  {'name': 'nidoran-m', 'url': 'https://pokeapi.co/api/v2/pokemon/32/'},
  {'name': 'nidorino', 'url': 'https://pokeapi.co/api/v2/pokemon/33/'},
  {'name': 'nidoking', 'url': 'https://pokeapi.co/api/v2/pokemon/34/'},
  {'name': 'clefairy', 'url': 'https://pokeapi.co/api/v2/pokemon/35/'},
  {'name': 'clefable', 'url': 'https://pokeapi.co/api/v2/pokemon/36/'},
  {'name': 'vulpix', 'url': 'https://pokeapi.co/api/v2/pokemon/37/'},
  {'name': 'ninetales', 'url': 'https://pokeapi.co/api/v2/pokemon/38/'},
  {'name': 'jigglypuff', 'url': 'https://pokeapi.co/api/v2/pokemon/39/'},
  {'name': 'wigglytuff', 'url': 'https://pokeapi.co/api/v2/pokemon/40/'},
  {'name': 'zubat', 'url': 'https://pokeapi.co/api/v2/pokemon/41/'},
  {'name': 'golbat', 'url': 'https://pokeapi.co/api/v2/pokemon/42/'},
  {'name': 'oddish', 'url': 'https://pokeapi.co/api/v2/pokemon/43/'},
  {'name': 'gloom', 'url': 'https://pokeapi.co/api/v2/pokemon/44/'},
  {'name': 'vileplume', 'url': 'https://pokeapi.co/api/v2/pokemon/45/'},
  {'name': 'paras', 'url': 'https://pokeapi.co/api/v2/pokemon/46/'},
  {'name': 'parasect', 'url': 'https://pokeapi.co/api/v2/pokemon/47/'},
  {'name': 'venonat', 'url': 'https://pokeapi.co/api/v2/pokemon/48/'},
  {'name': 'venomoth', 'url': 'https://pokeapi.co/api/v2/pokemon/49/'},
  {'name': 'diglett', 'url': 'https://pokeapi.co/api/v2/pokemon/50/'},
  {'name': 'dugtrio', 'url': 'https://pokeapi.co/api/v2/pokemon/51/'},
  {'name': 'meowth', 'url': 'https://pokeapi.co/api/v2/pokemon/52/'},
  {'name': 'persian', 'url': 'https://pokeapi.co/api/v2/pokemon/53/'},
  {'name': 'psyduck', 'url': 'https://pokeapi.co/api/v2/pokemon/54/'},
  {'name': 'golduck', 'url': 'https://pokeapi.co/api/v2/pokemon/55/'},
  {'name': 'mankey', 'url': 'https://pokeapi.co/api/v2/pokemon/56/'},
  {'name': 'primeape', 'url': 'https://pokeapi.co/api/v2/pokemon/57/'},
  {'name': 'growlithe', 'url': 'https://pokeapi.co/api/v2/pokemon/58/'},
  {'name': 'arcanine', 'url': 'https://pokeapi.co/api/v2/pokemon/59/'},
  {'name': 'poliwag', 'url': 'https://pokeapi.co/api/v2/pokemon/60/'},
  {'name': 'poliwhirl', 'url': 'https://pokeapi.co/api/v2/pokemon/61/'},
  {'name': 'poliwrath', 'url': 'https://pokeapi.co/api/v2/pokemon/62/'},
  {'name': 'abra', 'url': 'https://pokeapi.co/api/v2/pokemon/63/'},
  {'name': 'kadabra', 'url': 'https://pokeapi.co/api/v2/pokemon/64/'},
  {'name': 'alakazam', 'url': 'https://pokeapi.co/api/v2/pokemon/65/'},
  {'name': 'machop', 'url': 'https://pokeapi.co/api/v2/pokemon/66/'},
  {'name': 'machoke', 'url': 'https://pokeapi.co/api/v2/pokemon/67/'},
  {'name': 'machamp', 'url': 'https://pokeapi.co/api/v2/pokemon/68/'},
  {'name': 'bellsprout', 'url': 'https://pokeapi.co/api/v2/pokemon/69/'},
  {'name': 'weepinbell', 'url': 'https://pokeapi.co/api/v2/pokemon/70/'},
  {'name': 'victreebel', 'url': 'https://pokeapi.co/api/v2/pokemon/71/'},
  {'name': 'tentacool', 'url': 'https://pokeapi.co/api/v2/pokemon/72/'},
  {'name': 'tentacruel', 'url': 'https://pokeapi.co/api/v2/pokemon/73/'},
  {'name': 'geodude', 'url': 'https://pokeapi.co/api/v2/pokemon/74/'},
  {'name': 'graveler', 'url': 'https://pokeapi.co/api/v2/pokemon/75/'},
  {'name': 'golem', 'url': 'https://pokeapi.co/api/v2/pokemon/76/'},
  {'name': 'ponyta', 'url': 'https://pokeapi.co/api/v2/pokemon/77/'},
  {'name': 'rapidash', 'url': 'https://pokeapi.co/api/v2/pokemon/78/'},
  {'name': 'slowpoke', 'url': 'https://pokeapi.co/api/v2/pokemon/79/'},
  {'name': 'slowbro', 'url': 'https://pokeapi.co/api/v2/pokemon/80/'},
  {'name': 'magnemite', 'url': 'https://pokeapi.co/api/v2/pokemon/81/'},
  {'name': 'magneton', 'url': 'https://pokeapi.co/api/v2/pokemon/82/'},
  {'name': 'farfetchd', 'url': 'https://pokeapi.co/api/v2/pokemon/83/'},
  {'name': 'doduo', 'url': 'https://pokeapi.co/api/v2/pokemon/84/'},
  {'name': 'dodrio', 'url': 'https://pokeapi.co/api/v2/pokemon/85/'},
  {'name': 'seel', 'url': 'https://pokeapi.co/api/v2/pokemon/86/'},
  {'name': 'dewgong', 'url': 'https://pokeapi.co/api/v2/pokemon/87/'},
  {'name': 'grimer', 'url': 'https://pokeapi.co/api/v2/pokemon/88/'},
  {'name': 'muk', 'url': 'https://pokeapi.co/api/v2/pokemon/89/'},
  {'name': 'shellder', 'url': 'https://pokeapi.co/api/v2/pokemon/90/'},
  {'name': 'cloyster', 'url': 'https://pokeapi.co/api/v2/pokemon/91/'},
  {'name': 'gastly', 'url': 'https://pokeapi.co/api/v2/pokemon/92/'},
  {'name': 'haunter', 'url': 'https://pokeapi.co/api/v2/pokemon/93/'},
  {'name': 'gengar', 'url': 'https://pokeapi.co/api/v2/pokemon/94/'},
  {'name': 'onix', 'url': 'https://pokeapi.co/api/v2/pokemon/95/'},
  {'name': 'drowzee', 'url': 'https://pokeapi.co/api/v2/pokemon/96/'},
  {'name': 'hypno', 'url': 'https://pokeapi.co/api/v2/pokemon/97/'},
  {'name': 'krabby', 'url': 'https://pokeapi.co/api/v2/pokemon/98/'},
  {'name': 'kingler', 'url': 'https://pokeapi.co/api/v2/pokemon/99/'},
  {'name': 'voltorb', 'url': 'https://pokeapi.co/api/v2/pokemon/100/'},
  {'name': 'electrode', 'url': 'https://pokeapi.co/api/v2/pokemon/101/'},
  {'name': 'exeggcute', 'url': 'https://pokeapi.co/api/v2/pokemon/102/'},
  {'name': 'exeggutor', 'url': 'https://pokeapi.co/api/v2/pokemon/103/'},
  {'name': 'cubone', 'url': 'https://pokeapi.co/api/v2/pokemon/104/'},
  {'name': 'marowak', 'url': 'https://pokeapi.co/api/v2/pokemon/105/'},
  {'name': 'hitmonlee', 'url': 'https://pokeapi.co/api/v2/pokemon/106/'},
  {'name': 'hitmonchan', 'url': 'https://pokeapi.co/api/v2/pokemon/107/'},
  {'name': 'lickitung', 'url': 'https://pokeapi.co/api/v2/pokemon/108/'},
  {'name': 'koffing', 'url': 'https://pokeapi.co/api/v2/pokemon/109/'},
  {'name': 'weezing', 'url': 'https://pokeapi.co/api/v2/pokemon/110/'},
  {'name': 'rhyhorn', 'url': 'https://pokeapi.co/api/v2/pokemon/111/'},
  {'name': 'rhydon', 'url': 'https://pokeapi.co/api/v2/pokemon/112/'},
  {'name': 'chansey', 'url': 'https://pokeapi.co/api/v2/pokemon/113/'},
  {'name': 'tangela', 'url': 'https://pokeapi.co/api/v2/pokemon/114/'},
  {'name': 'kangaskhan', 'url': 'https://pokeapi.co/api/v2/pokemon/115/'},
  {'name': 'horsea', 'url': 'https://pokeapi.co/api/v2/pokemon/116/'},
  {'name': 'seadra', 'url': 'https://pokeapi.co/api/v2/pokemon/117/'},
  {'name': 'goldeen', 'url': 'https://pokeapi.co/api/v2/pokemon/118/'},
  {'name': 'seaking', 'url': 'https://pokeapi.co/api/v2/pokemon/119/'},
  {'name': 'staryu', 'url': 'https://pokeapi.co/api/v2/pokemon/120/'},
  {'name': 'starmie', 'url': 'https://pokeapi.co/api/v2/pokemon/121/'},
  {'name': 'mr-mime', 'url': 'https://pokeapi.co/api/v2/pokemon/122/'},
  {'name': 'scyther', 'url': 'https://pokeapi.co/api/v2/pokemon/123/'},
  {'name': 'jynx', 'url': 'https://pokeapi.co/api/v2/pokemon/124/'},
  {'name': 'electabuzz', 'url': 'https://pokeapi.co/api/v2/pokemon/125/'},
  {'name': 'magmar', 'url': 'https://pokeapi.co/api/v2/pokemon/126/'},
  {'name': 'pinsir', 'url': 'https://pokeapi.co/api/v2/pokemon/127/'},
  {'name': 'tauros', 'url': 'https://pokeapi.co/api/v2/pokemon/128/'},
  {'name': 'magikarp', 'url': 'https://pokeapi.co/api/v2/pokemon/129/'},
  {'name': 'gyarados', 'url': 'https://pokeapi.co/api/v2/pokemon/130/'},
  {'name': 'lapras', 'url': 'https://pokeapi.co/api/v2/pokemon/131/'},
  {'name': 'ditto', 'url': 'https://pokeapi.co/api/v2/pokemon/132/'},
  {'name': 'eevee', 'url': 'https://pokeapi.co/api/v2/pokemon/133/'},
  {'name': 'vaporeon', 'url': 'https://pokeapi.co/api/v2/pokemon/134/'},
  {'name': 'jolteon', 'url': 'https://pokeapi.co/api/v2/pokemon/135/'},
  {'name': 'flareon', 'url': 'https://pokeapi.co/api/v2/pokemon/136/'},
  {'name': 'porygon', 'url': 'https://pokeapi.co/api/v2/pokemon/137/'},
  {'name': 'omanyte', 'url': 'https://pokeapi.co/api/v2/pokemon/138/'},
  {'name': 'omastar', 'url': 'https://pokeapi.co/api/v2/pokemon/139/'},
  {'name': 'kabuto', 'url': 'https://pokeapi.co/api/v2/pokemon/140/'},
  {'name': 'kabutops', 'url': 'https://pokeapi.co/api/v2/pokemon/141/'},
  {'name': 'aerodactyl', 'url': 'https://pokeapi.co/api/v2/pokemon/142/'},
  {'name': 'snorlax', 'url': 'https://pokeapi.co/api/v2/pokemon/143/'},
  {'name': 'articuno', 'url': 'https://pokeapi.co/api/v2/pokemon/144/'},
  {'name': 'zapdos', 'url': 'https://pokeapi.co/api/v2/pokemon/145/'},
  {'name': 'moltres', 'url': 'https://pokeapi.co/api/v2/pokemon/146/'},
  {'name': 'dratini', 'url': 'https://pokeapi.co/api/v2/pokemon/147/'},
  {'name': 'dragonair', 'url': 'https://pokeapi.co/api/v2/pokemon/148/'},
  {'name': 'dragonite', 'url': 'https://pokeapi.co/api/v2/pokemon/149/'},
  {'name': 'mewtwo', 'url': 'https://pokeapi.co/api/v2/pokemon/150/'},
  {'name': 'mew', 'url': 'https://pokeapi.co/api/v2/pokemon/151/'}]}

In [19]:
"""Extract:
name
height
weight
base_experience
first type"""
pokemon_1to151=[]

for pokemon_id in range (1,152) :
    response = requests.get(f"https://pokeapi.co/api/v2/pokemon/{pokemon_id}", timeout=10)
    response.raise_for_status()
    data = response.json()
    pokemon_1to151.append({"id":data["id"], "name":data["name"], "height":data["height"], "weight": data["weight"], "base_experience": data ["base_experience"],"first_type": data["types"][0]["type"]["name"] 
                          })
    time.sleep(0.5)


df_pokemon = pd.DataFrame(pokemon_1to151)
display(len(pokemon_1to151))

151

In [20]:
"""Create a DataFrame"""
df_pokemon = pd.DataFrame(pokemon_1to151)
display(df_pokemon)

      id        name  height  weight  base_experience first_type
0      1   bulbasaur       7      69               64      grass
1      2     ivysaur      10     130              142      grass
2      3    venusaur      20    1000              236      grass
3      4  charmander       6      85               62       fire
4      5  charmeleon      11     190              142       fire
..   ...         ...     ...     ...              ...        ...
146  147     dratini      18      33               60     dragon
147  148   dragonair      40     165              147     dragon
148  149   dragonite      22    2100              270     dragon
149  150      mewtwo      20    1220              306    psychic
150  151         mew       4      40              270    psychic

[151 rows x 6 columns]

In [21]:
"""Add a new column:weight_kg (divide weight by 10)"""
df_pokemon["weight_kg"]=df_pokemon["weight"]/10



display(df_pokemon)

      id        name  height  weight  base_experience first_type  weight_kg
0      1   bulbasaur       7      69               64      grass        6.9
1      2     ivysaur      10     130              142      grass       13.0
2      3    venusaur      20    1000              236      grass      100.0
3      4  charmander       6      85               62       fire        8.5
4      5  charmeleon      11     190              142       fire       19.0
..   ...         ...     ...     ...              ...        ...        ...
146  147     dratini      18      33               60     dragon        3.3
147  148   dragonair      40     165              147     dragon       16.5
148  149   dragonite      22    2100              270     dragon      210.0
149  150      mewtwo      20    1220              306    psychic      122.0
150  151         mew       4      40              270    psychic        4.0

[151 rows x 7 columns]

In [22]:
"""Answer:"""

"""Which Pokémon is the heaviest?"""

heaviest = df_pokemon.loc[df_pokemon["weight_kg"].idxmax()]
heaviest

id                     143
name               snorlax
height                  21
weight                4600
base_experience        189
first_type          normal
weight_kg            460.0
Name: 142, dtype: object

In [23]:
"""What is the average weight?"""
average_weight=df_pokemon["weight_kg"].mean()
print(f"the average weight is {average_weight.round(2)} kg")

the average weight is 45.95 kg

In [25]:
"""How many Pokémon are there per type?"""
count_per_type=df_pokemon["first_type"].value_counts()
count_per_type

first_type
water       28
normal      22
poison      14
grass       12
fire        12
bug         12
electric     9
rock         9
ground       8
psychic      8
fighting     7
ghost        3
dragon       3
fairy        2
ice          2
Name: count, dtype: int64

In [38]:
"""Which type has the highest average weight?"""
highest_average_weight_per_type=df_pokemon.groupby("first_type")["weight_kg"].mean().idxmax()

average_weight_per_type=df_pokemon.groupby("first_type")["weight_kg"].mean()
average_weight_per_type["rock"]

print(f"{highest_average_weight_per_type} has the highest average weight, with {average_weight_per_type["rock"].round(2)} kg")

rock has the highest average weight, with 87.61 kg

# Challenge 2: Crypto Market Analysis

## Goal

Analyze cryptocurrency prices using real-time data.

## Tasks

1. Get prices for:
   - bitcoin
   - ethereum
   - solana
   - dogecoin

2. Convert the response into a DataFrame (coins as rows)

3. Rename columns properly

4. Add:
   - price_rank (ranking by price)
   - price_category:
        - "high" if > 1000  
        - "medium" if between 100 and 1000  
        - "low" if < 100  

5. Answer:
   - Which coin is the most expensive?
   - Which category has more coins?

6. **Bonus**:
   - Create a column with price difference vs bitcoin

In [48]:
# starter code
import os
import requests
import pandas as pd

url = "https://api.coingecko.com/api/v3/simple/price"

params = {"ids": "bitcoin,ethereum,solana,dogecoin","vs_currencies":"usd",}


response = requests.get(url,params=params, timeout =10)

response.raise_for_status()
price_data = response.json()
print(price_data)

{'bitcoin': {'usd': 80808}, 'ethereum': {'usd': 2347.36}, 'solana': {'usd': 101.14}, 'dogecoin': {'usd': 0.078708}}

In [51]:
"""Convert the response into a DataFrame (coins as rows)"""
df_crypto = pd.DataFrame(price_data).T
df_crypto

                   usd
bitcoin   80808.000000
ethereum   2347.360000
solana      101.140000
dogecoin      0.078708

In [70]:
"""Rename columns properly"""
df_crypto = (pd.DataFrame.from_dict(price_data, orient="index").reset_index(names="coins").rename(columns={"usd":"price_in_usd"}))
df_crypto

      coins  price_in_usd
0   bitcoin  80808.000000
1  ethereum   2347.360000
2    solana    101.140000
3  dogecoin      0.078708

In [73]:
"""price_rank (ranking by price)"""


df_crypto=df_crypto.sort_values(by=["price_in_usd"], ascending=False)
display(df_crypto)

      coins  price_in_usd
0   bitcoin  80808.000000
1  ethereum   2347.360000
2    solana    101.140000
3  dogecoin      0.078708

In [77]:
"""price_category:
"high" if > 1000
"medium" if between 100 and 1000
"low" if < 100"""

import numpy as np
conditions = [df_crypto["price_in_usd"]>1000,(df_crypto["price_in_usd"]>=100)&(df_crypto["price_in_usd"]<=1000),df_crypto["price_in_usd"]<100]
values =["high","medium","low"]
df_crypto["price_category"] = np.select(conditions, values, default="unknown")
df_crypto

      coins  price_in_usd price_category
0   bitcoin  80808.000000           high
1  ethereum   2347.360000           high
2    solana    101.140000         medium
3  dogecoin      0.078708            low

In [79]:
"""Which coin is the most expensive?"""
most_expensive =df_crypto.loc[df_crypto["price_in_usd"].idxmax(),"coins"]
display(f"the most expensive coin is {most_expensive}")

'the most expensive coin isbitcoin'

In [88]:
"""Which category has more coins?"""
category_more_coins=df_crypto["price_category"].value_counts().idxmax()
display(f"the category who has the more coins is {category_more_coins}")

'the category who has the more coins is high'